//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geo.Localization.Services.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ROffice {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ROffice() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geo.Localization.Services.Texts.ROffice", typeof(ROffice).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe and the Middle East.
        /// </summary>
        public static string AddressRoad {
            get {
                return ResourceManager.GetString("AddressRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Localization Global Headquarters Receptionist.
        /// </summary>
        public static string AddressStateAndCode {
            get {
                return ResourceManager.GetString("AddressStateAndCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Localization is the leading source of information and insight in critical areas that shape today&apos;s business landscape. Customers around the world rely on us to address strategic and operational challenges..
        /// </summary>
        public static string CompanyAbout {
            get {
                return ResourceManager.GetString("CompanyAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Localization.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Geo Localization&lt;/strong&gt; Geo Localizations.
        /// </summary>
        public static string CompanyNameMore {
            get {
                return ResourceManager.GetString("CompanyNameMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to osvaldo.martini@gmail.com.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday 12:00am (UTC) to Saturday 12:00am (UTC).
        /// </summary>
        public static string HoursWork {
            get {
                return ResourceManager.GetString("HoursWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +44(0) 7951 144 116.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
    }
}
